### ISSUE TITLE
Anyway to avoid etcd dependency when it's not needed?

### ISSUE THREAD

**Issue by fengye87** [kubernetes-sigs/apiserver-runtime#44] opened 2021-03-29 07:47 UTC
I'm building an apiserver with this project which doesn't use etcd as backend. However, the resulting binary still requires a `--etcd-servers` flag to get started normally, and it would keep connecting to that address until a real etcd service is connectd. And during this connecting period, the api endpoint would keep returning 503 error.

So, is there anyway I can avoid the etcd dep? If not, any suggestion to how to make it possible? I may compose a PR here.

**Comment by yue9944882** [comment] 2021-04-13 09:31
@fengye87 i think it's a duplicate of https://github.com/kubernetes-sigs/apiserver-builder-alpha/issues/583. and i will get back w/ feasible fixes after reproducing that locally.

**Comment by yue9944882** [comment] 2021-04-13 10:18
https://github.com/kubernetes-sigs/apiserver-builder-alpha/issues/583#issuecomment-818620597 @fengye87 i saw a few warning level loggings from the apiserver when it's actually working w/o etcd, but the custom resources will be working fine. the e2e test https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/587 also confirms that..

**Comment by yue9944882** [comment] 2021-04-16 08:01
@fengye87 i cut a new release of apiserver-runtime in which etcd dependency can be completely removed by having `WithoutEtcd()` in the builder flow. can you try?

**Comment by fengye87** [comment] 2021-04-19 01:57
@yue9944882 I can confirm `WithoutEtcd()` works as expected, but doesn't solve my problem entirely.

I've created a [sample](https://github.com/fengye87/sample-apiserver) to demonstrate my requirements. A few key points here:

* A dummy resource `Foo`, ideally without any CRUD endpoints
* A subresource `Bar`, which answers only to the Connect verb and has custom implementation
* None of the above resources requires Etcd

In the previous commit of the sample, I can get it work but with an Etcd. In the current commit, I can remove the Etcd dependency only if I add one of CRUD operations to `Foo`, which would effectively disable the discovery of  subresource `Bar` due to https://github.com/kubernetes-sigs/apiserver-runtime/blob/main/pkg/builder/builder_resource.go#L73. Moreover, if I do not add any CRUD operations to `Foo`, I have to provide a `RESTOptionsGetter` to the builder flow to avoid some nil pointers while starting the server. However, I still get a `etcdclient: no available endpoints` error with a proper `RESTOptionsGetter`.

**Comment by yue9944882** [comment] 2021-04-28 08:54
> A dummy resource Foo, ideally without any CRUD endpoints

@fengye87 for `Foo` resource, just implementing `resource.Object` interface should be fine which will makes it a classic kubernetes resource. i'm not sure if all CRUD endpoints can be disabled at all but it doesn't seem to be a blocker for your case, is it? 

> A subresource Bar, which answers only to the Connect verb and has custom implementation

in the latest release of apiserver-runtime (v1.0.1), you can implement `resource.ConnectorSubResource` interface for your `Bar` definitions. Meanwhile, you're supposed to setup the connection between `Foo` and `Bar` as is shown in [this example](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/98d2776a996221c7ed750a554c6f9b3a7398d06d/example/podexec/pkg/apis/podexec/v1/pod_types.go#L87-L91). basically i think your case is really close to the example project [pod-exec](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/example/podexec/pkg/apis/podexec/v1/pod_exec.go) from our peer project.

**Comment by fengye87** [comment] 2021-04-28 14:05
@yue9944882 I've just had a look at the example project pod-exec you mentioned, it is very close to my sample. Can the pod-exec apiserver run without etcd? In my sample project, as soon as I introduced the `WithoutEtcd` option, my apiserver just refuse to start up.

**Closed** 2021-09-25 14:55 UTC
Labels: lifecycle/rotten
